import { Product } from './src/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    product_id: 'PRD_FIMA_EXP_1_0',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer with shower set',
    model_number: 'FIMA-EXP-1',
    description: 'Exposed bath mixer with shower set from FIMA Carlo Frattini.',
    base_price: 20000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_1_0.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_2_1',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer without shower set',
    model_number: 'FIMA-EXP-2',
    description: 'Exposed bath mixer without shower set from FIMA Carlo Frattini.',
    base_price: 19000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_2_1.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_3_2',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath tap with shower set',
    model_number: 'FIMA-EXP-3',
    description: 'Exposed bath tap with shower set from FIMA Carlo Frattini.',
    base_price: 23000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_3_2.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_4_3',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer without shower set',
    model_number: 'FIMA-EXP-4',
    description: 'Exposed bath mixer without shower set from FIMA Carlo Frattini.',
    base_price: 16000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_4_3.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_5_4',
    category: 'Exposed Bath Mixer',
    product_name: 'Thermostatic bath and shower mixer for concealed installation 2 outlets with shower set',
    model_number: 'FIMA-EXP-5',
    description: 'Thermostatic bath and shower mixer for concealed installation 2 outlets with shower set from FIMA Carlo Frattini.',
    base_price: 20000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_5_4.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_6_5',
    category: 'Exposed Bath Mixer',
    product_name: 'Single lever bath and shower mixer for concealed installation 2 outlets with shower set',
    model_number: 'FIMA-EXP-6',
    description: 'Single lever bath and shower mixer for concealed installation 2 outlets with shower set from FIMA Carlo Frattini.',
    base_price: 21000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_6_5.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_7_6',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer without shower set',
    model_number: 'FIMA-EXP-7',
    description: 'Exposed bath mixer without shower set from FIMA Carlo Frattini.',
    base_price: 16000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_7_6.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_8_7',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath tap with shower set',
    model_number: 'FIMA-EXP-8',
    description: 'Exposed bath tap with shower set from FIMA Carlo Frattini.',
    base_price: 16000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_8_7.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_9_8',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer without shower set',
    model_number: 'FIMA-EXP-9',
    description: 'Exposed bath mixer without shower set from FIMA Carlo Frattini.',
    base_price: 20000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_9_8.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_10_9',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer with shower set',
    model_number: 'FIMA-EXP-10',
    description: 'Exposed bath mixer with shower set from FIMA Carlo Frattini.',
    base_price: 16000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_10_9.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_11_10',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer with shower set',
    model_number: 'FIMA-EXP-11',
    description: 'Exposed bath mixer with shower set from FIMA Carlo Frattini.',
    base_price: 23000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_11_10.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_12_11',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer without shower set',
    model_number: 'FIMA-EXP-12',
    description: 'Exposed bath mixer without shower set from FIMA Carlo Frattini.',
    base_price: 18000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_12_11.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_13_12',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer with shower set',
    model_number: 'FIMA-EXP-13',
    description: 'Exposed bath mixer with shower set from FIMA Carlo Frattini.',
    base_price: 18000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_13_12.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_14_13',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer without shower set',
    model_number: 'FIMA-EXP-14',
    description: 'Exposed bath mixer without shower set from FIMA Carlo Frattini.',
    base_price: 18000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_14_13.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_15_14',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer with shower set',
    model_number: 'FIMA-EXP-15',
    description: 'Exposed bath mixer with shower set from FIMA Carlo Frattini.',
    base_price: 20000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_15_14.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  },
  {
    product_id: 'PRD_FIMA_EXP_16_15',
    category: 'Exposed Bath Mixer',
    product_name: 'Exposed bath mixer without shower set',
    model_number: 'FIMA-EXP-16',
    description: 'Exposed bath mixer without shower set from FIMA Carlo Frattini.',
    base_price: 17000,
    gst_percentage: 18,
    hsn_code: '84818020',
    unit: 'PCS',
    main_image_url: '/products/fima_exp_16_15.jpg',
    status: 'ACTIVE',
    customizable: 'YES',
    image_mode: 'COMBINATION_IMAGE',
    created_at: '2026-09-02 10:00:00',
    updated_at: '2026-09-02 10:00:00'
  }
];